root: true

env:
  es6: true
  node: true
  mocha: true
  browser: true

globals:
  serviceworker: true
  describe: true
  browser: true
  fetch: true
  it: true
  expect: true
  document: true

parserOptions:
  ecmaVersion: 2020
  ecmaFeatures:
    jsx: true
    generators: true
    impliedStrict: false
    legacyDecorators: true
    experimentalDecorators: true
    experimentalObjectRestSpread: true

settings:
  react:
    version: detect

parser: babel-eslint

plugins:
- fp
- babel
- react
- react-hooks
- jsx-a11y

extends:
- plugin:jsx-a11y/recommended
- plugin:react/recommended
- eslint:recommended
- react-app

rules:
  accessor-pairs: 'off'
  capitalized-comments: 'off'
  consistent-return: warn
  linebreak-style: 'off'
  no-bitwise: warn
  no-useless-concat: warn
  space-before-function-paren: 'off'
  brace-style:
  - error
  - 1tbs
  comma-spacing:
  - error
  - after: true
    before: false
  comma-dangle:
  - error
  - always-multiline
  camelcase: error
  callback-return: error
  dot-location:
  - error
  - property
  dot-notation: error
  eol-last: error
  eqeqeq:
  - error
  - allow-null
  global-require: error
  handle-callback-err: error
  indent:
  - warn
  - 2
  - SwitchCase: 1
    ignoredNodes:
    - TemplateLiteral
  keyword-spacing:
  - error
  - after: true
    before: true
  key-spacing:
  - warn
  - singleLine:
      beforeColon: false
      afterColon: true
    multiLine:
      align: colon
      mode: minimum
  max-len:
  - error
  - code: 120
    ignoreUrls: true
    ignoreStrings: true
    ignoreComments: true
    ignoreTrailingComments: true
  no-var: error
  no-tabs: error
  no-debugger: error
  no-console:
  - warn
  - allow:
    - info
    - warn
    - error
  no-inner-declarations:
  - error
  - functions
  no-restricted-syntax:
  - error
  - WithStatement
  no-shadow:
  - error
  - hoist: never
  no-unused-expressions: warn
  no-param-reassign: warn
  no-unused-vars:
  - warn
  - args: none
    ignoreRestSiblings: true
  no-duplicate-imports: error
  no-use-before-define:
  - error
  - functions: false
    variables: false
  no-multiple-empty-lines:
  - error
  - max: 1
    maxEOF: 0
    maxBOF: 0
  no-multi-spaces:
  - error
  - exceptions:
      Property: true
      VariableDeclarator: true
      ImportDeclaration: true
  no-new-require: error
  no-mixed-requires: error
  no-octal: error
  no-octal-escape: error
  operator-linebreak:
  - warn
  - after
  - overrides:
      "?": before
      ":": before
  prefer-const: warn
  quotes:
  - error
  - single
  - avoidEscape: true
    allowTemplateLiterals: true
  semi:
  - error
  - never
  semi-spacing:
  - error
  - before: false
    after: true
  # space-in-parens:
  # - error
  # - never
  space-before-blocks: error
  array-bracket-spacing:
  - 2
  - always
  strict:
  - warn
  - global
  valid-typeof:
  - error
  - requireStringLiterals: true
  jsx-quotes:
  - error
  - prefer-single
  max-lines:
  - warn
  - 200
  max-lines-per-function:
  - warn
  - max: 100
    skipComments: true
    skipBlankLines: true
  complexity:
  - warn
  - 20
  max-nested-callbacks:
  - error
  - 3
  max-depth:
  - error
  - 3

  ## REACT RULES
  react/display-name: 'off'
  react/jsx-filename-extension: 'off'
  react/prop-types: warn
  react/no-array-index-key: warn
  react/jsx-uses-vars: error
  react/jsx-uses-react: error
  react/jsx-curly-spacing:
  - error
  - always
  react/jsx-indent:
  - error
  - 2
  react/prefer-es6-class: warn
  react/prefer-stateless-function: warn

  ## REACT HOOKS RULES
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn

  ## FUNCTIONAL PROGRAMMING RULES
  fp/no-let: warn
  fp/no-delete: error
  fp/no-get-set: error
  fp/no-arguments: error
  fp/no-mutating-assign: warn
  fp/no-mutating-methods: 'off'
  fp/no-valueof-field: error
  fp/no-throw: warn